# Generated by Django 3.2.4 on 2021-08-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
