# Generated by Django 3.2.4 on 2021-08-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AddField(
            model_name='person',
            name='upi',
            field=models.CharField(default='', max_length=10),
        ),
    ]
